name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify
      
      - name: Deploy to ppwww
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './public/.'
          remote: '~/www'
          host: ${{secrets.PPWWW_IP}}
          port: ${{secrets.PPWWW_PORT}}
          user: ${{secrets.PPWWW_USER}} 
          key: ${{secrets.PPWWW_PRIVATE_KEY}}
          pre_upload: echo "This will be executed pre the upload!"
          post_upload: echo "This will be executed after the upload!"
          scp_options: -v

      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public